car:
    path:     /
    defaults: { _controller: "InzReportsBundle:Car:index" }

car_show:
    path:     /{id}/show
    defaults: { _controller: "InzReportsBundle:Car:show" }

car_new:
    path:     /new
    defaults: { _controller: "InzReportsBundle:Car:new" }
    
car_edit:
    path:     /{id}/edit
    defaults: { _controller: "InzReportsBundle:Car:edit" }

car_delete:
    path:     /{id}/delete
    defaults: { _controller: "InzReportsBundle:Car:delete" }
    requirements: { _method: post|delete }
    
car_refuel:
    path:     /{id}/refuel
    defaults: { _controller: "InzReportsBundle:Car:refuel" }
    
# get engine types for given fuel id    
car_get_engine_type:
    path:     /engineType/{fuelTypeId}
    defaults: { _controller: "InzReportsBundle:Car:ajaxGetEngineType" }
    options:
        expose: true
